---
verifier:
  name: inspec
  inspec_tests:
    - cookbooks/aws-parallelcluster-computefleet/test

suites:
  - name: clusterstatusmgtd
    run_list:
      - recipe[aws-parallelcluster-tests::setup]
      - recipe[aws-parallelcluster-computefleet::clusterstatusmgtd_config]
    verifier:
      controls:
        - /tag:config_clusterstatusmgtd/
    attributes:
      dependencies:
        - recipe:aws-parallelcluster-platform::users
        - recipe:aws-parallelcluster-platform::sudo_install
      cluster:
        node_type: 'HeadNode'
  - name: fleet_status
    run_list:
      - recipe[aws-parallelcluster-tests::setup]
      - recipe[aws-parallelcluster-computefleet::fleet_status]
    verifier:
      controls:
        - /tag:config_fleet_status/
    attributes:
      dependencies:
        - recipe:aws-parallelcluster-tests::docker_mock
      cluster:
        stack_name: "mock"
        node_type: HeadNode
        ddb_table: <%= ENV['DDB_TABLE'] %>
  - name: finalize_custom_parallelcluster_node
    run_list:
      - recipe[aws-parallelcluster-tests::setup]
      - recipe[aws-parallelcluster-entrypoints::finalize]
    verifier:
      controls:
        - /node_virtualenv_created/
        - custom_parallelcluster_node_installed
    attributes:
      cluster:
        custom_node_package: https://github.com/aws/aws-parallelcluster-node/archive/develop.tar.gz
        python-version: 3.9.16
        node_virtualenv_path: /opt/parallelcluster/pyenv/versions/node_virtualenv
  - name: test_attach_login_node
    run_list:
      - recipe[aws-parallelcluster-tests::setup]
      - recipe[aws-parallelcluster-computefleet::config_login_node]
    attributes:
      dependencies:
        - resource:package_repos
        # TODO: remove this and move Slurm dependencies into the appropriate Slurm recipes
        - resource:install_packages
      cluster:
        # TODO: this is just a set of convenience variables for the kitchen test: in reality we will have everything
        # available from the dna.json
        head_node_private_ip: 10.0.0.88
        node_type: Login
        shared_dir_head: /opt/parallelcluster/shared
        head_node_home_path: /home
        dns_domain: test-login-node-01.pcluster
